### PR TITLE
SetWindowLongPtr on 32-bit

### LINKED ISSUE #385: SetWindowLongPtr on 32-bit
[This is an issue about my recent PR [384](https://github.com/AArnott/pinvoke/pull/384)]

According to the documentation for [SetWindowLongPtr](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644898(v=vs.85).aspx), 

>  When compiling for 32-bit Windows, SetWindowLongPtr is defined as a call to the SetWindowLong function.

What this really means is that calls to `PInvoke.User32.SetWindowLongPtr` on 32-bit processes will (and do) result in an `EntryPointNotFoundException`

Thoughts on how to, or whether to, fix this? 

I feel like this should be fixed, by exposing `SetWindowLongPtr `through `User32.Helpers.cs` and conditionally calling `SetWindowLongPtr `on 64-bit vs. `SetWindowLong `on 32-bit. 

If no objections, I'll submit another PR.

### PR DESCRIPTION
**Pull request by ghost**
According to the documentation for `SetWindowLongPtr`,

> When compiling for 32-bit Windows, `SetWindowLongPtr` is defined as a call to the `SetWindowLong` function.

What this really means is that calls to `PInvoke.User32.SetWindowLongPtr` on 32-bit processes will (and do) result in an `EntryPointNotFoundException`

This fix exposes `SetWindowLongPtr` through `User32.Helpers.cs` by conditionally calling `SetWindowLongPtr` on 64-bit vs. `SetWindowLong` on 32-bit.

Also, adding a test. 

Fixes #385

### CODE REVIEW

File: src/User32/User32.cs [hunk 1]
```diff
@@ -3647,5 +3569,27 @@ public static partial class User32
...
+        /// <para>If the previous value is zero and the function succeeds, the return value is zero, but the function does
+        /// not clear the last error information. To determine success or failure, clear the last error information by
+        /// calling SetLastError with 0, then call SetWindowLongPtr. Function failure will be indicated by a return value of
+        /// zero and a GetLastError result that is nonzero.</para>
+        /// </returns>
+        /// <remarks>
+        /// When compiling for 32-bit Windows, SetWindowLongPtr is defined as a call to the SetWindowLong function. This
+        /// function is exposed using a helper that conditionally calls SetWindowLong in 32-bit processes.
+        /// </remarks>
+        [DllImport(nameof(User32), SetLastError = true, EntryPoint = nameof(SetWindowLongPtr))]
```
Comment (AArnott) [inline src/User32/User32.cs]: I don't think we should use `nameof(SetWindowLongPtr)` for the `EntryPoint` here. That's the name of the helper method, and if we ever renamed that method, it would not be correct to change the string here.

File: src/User32/User32.Helpers.cs [hunk 2]
```diff
@@ -369,5 +369,93 @@ public static unsafe WINDOWPLACEMENT GetWindowPlacement(IntPtr hWnd)
...
+        /// </summary>
+        /// <param name="hWnd">A handle to the window and, indirectly, the class to which the window belongs.
+        /// The SetWindowLongPtr function fails if the process that owns the window specified by the
+        /// <paramref name="hWnd"/> parameter is at a higher process privilege in the UIPI hierarchy than the
+        /// process the calling thread resides in.</param>
+        /// <param name="nIndex">The zero-based offset to the value to be set. Valid values are in the range zero
+        /// through the number of bytes of extra window memory, minus the size of a LONG_PTR. To set any other value,
+        /// specify one of the following values.
+        ///
+        /// <list type="table">
```
Comment (AArnott) [inline src/User32/User32.Helpers.cs:385]: nice translation to xml! 😄

**Review by AArnott — CHANGES_REQUESTED** [review]
Looks great! Thank you for taking the time to test this. Just one small change please.

File: src/User32/User32.Helpers.cs (hunk 2 above)
Comment (ghost) [reply src/User32/User32.Helpers.cs:385]: Thanks, didn't know until now that "list" could mean "table" :)

File: src/User32/User32.cs (hunk 1 above)
Comment (ghost) [reply src/User32/User32.cs]: Done. Also, I added another definition as part of the latest commit (AdjustWindowRectEx). Just filling in the gaps as I find 'em.

**Review by AArnott — APPROVED** [review]
