### PR TITLE
Workaround for .NET Native toolchain issue

### LINKED ISSUE #377: UWP: Process initialization failed with status 0xc0000139
_From @CIPop on January 31, 2018 2:1_

A very simple UWP application using SDK 16299 will fail if compiled (AOT) with the following error when the binary is loaded:
"Process initialization failed with status 0xc0000139"

Activating "https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/show-loader-snaps" then running the app in a debugger shows the following issue:

`1725 3de8:3df4 @ 00384546 - LdrpProcessWork - ERROR: Unable to load DLL: "NTASN1.dll", Parent Module: "C:\WINDOWS\SYSTEM32\ncrypt.dll", Status: 0xc0000139`

_Copied from original issue: AArnott/PCLCrypto#137_

### PR DESCRIPTION
**Pull request by AArnott**
The issue is that SupportedAPIs-x86.xml and SupportedAPIs-x64.xml file, as found at
C:\Program Files (x86)\Windows Kits\10\App Certification Kit\SupportedAPIs-x??.xml
claim that some encoding-neutral methods are actually exported by Windows.
This leads .NET Native to generate bindings against them when they don't exist.

Until the Windows SDK is fixed, we workaround it by specifying the W unicode
suffix for the relevant methods directly.

Specifically changed are these methods:

* FirstFirstFileEx
* CreateMutex
* FormatMessage

Closes #377 by workaround

### CODE REVIEW

File: src/Kernel32/Kernel32.cs [hunk 1]
```diff
@@ -141,7 +141,7 @@ public static partial class Kernel32
         /// If the function succeeds, the return value is the number of TCHARs stored in the output buffer, excluding the terminating null character.
         /// If the function fails, the return value is zero. To get extended error information, call <see cref="GetLastError"/>.
         /// </returns>
-        [DllImport(api_ms_win_core_localization_l1_2_0, CharSet = CharSet.Unicode, SetLastError = true)]
+        [DllImport(api_ms_win_core_localization_l1_2_0, CharSet = CharSet.Unicode, EntryPoint = "FormatMessageW", ExactSpelling = true, SetLastError = true)]
```
Comment (tijoytom-zz) [inline src/Kernel32/Kernel32.cs:144]: You dont need ExactSpelling = true

Comment (AArnott) [reply src/Kernel32/Kernel32.cs:144]: Thanks for reviewing. It doesn't seem to do any harm either, so I'm going to leave it as a way of expressing that I add the `W` suffix so the system doesn't need to try.
I hope this is just a temporary workaround anyway till the Windows SDK is fixed.

Comment (tijoytom-zz) [reply src/Kernel32/Kernel32.cs:144]: Yes , we have a thread going with windows and there are more suffix free APIs that they added with no exports. Plan is to fix it by 4/6

Comment (tijoytom-zz) [reply src/Kernel32/Kernel32.cs:144]: => temporary workaround anyway till the Windows SDK is fixed.  
Forgot to mention that , using explicitly W or A is a good practice and i believe the  core recommendation is to use "W" always. So even after windows fix it , you should consider keeping this change.
